#!/bin/bash

npm install --prefix client && \
npm run bundle --prefix client && \
mvn package

java -jar target/server-*.jar $*
#java -DsocksProxyHost=localhost -DsocksProxyPort=7373 -jar target/server-*.jar $*

